---
# tasks file for backup
  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: install borg_backup
    yum:
      state: present
      name:
        - borgbackup

  - name: Create user borg
    user:
      name: borg

  - name: Creates directory /var/backup
    file:
      path: /var/backup
      state: directory
      mode: '0755'
      owner: borg
      group: borg


  - name: Mount /var/backup
    mount:
      path: "/var"
      src: /dev/sdb
      opts: bind
      state: mounted
      fstype: none

  - name: Creates directory .ssh
    file:
      path: /home/borg/.ssh
      state: directory
      mode: '0700'
      owner: borg
      group: borg



  - name: Create directory .authorized_keys
    file:
      path: /home/borg/.ssh/.authorized_keys
      state: directory
      mode: '0600'
      owner: borg
      group: borg

