---
# tasks file for backup
  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: install borg_backup
    yum:
      state: present
      name:
        - borgbackup

  - name: Create user borg
    user:
      name: borg


  - name: format disk sdb
    filesystem: dev=/dev/sdb fstype=ext4

  - name: Mount /var/backup
    mount:
      path: "/var/backup"
      src: /dev/sdb
      state: mounted
      fstype: ext4

  - name: Creates directory /var/backup
    file:
      path: /var/backup
      state: directory
      mode: '0700'
      owner: borg
      group: borg



  - name: Creates directory .ssh
    file:
      path: /home/borg/.ssh
      state: directory
      mode: '0700'
      owner: borg
      group: borg



  # - name: Create directory authorized_keys
  #   file:
  #     path: /home/borg/.ssh/authorized_keys
  #     state: directory
  #     mode: '0600'
  #     owner: borg
  #     group: borg

  - name: copy ssh-key
    template:
       src: roles/backup/files/client/root/.ssh/id_rsa.pub 
       dest:  /home/borg/.ssh/

  - name: name file
    shell: mv /home/borg/.ssh/id_rsa.pub /home/borg/.ssh/authorized_keys

  - name: chown
    file:
      path: /home/borg/.ssh/authorized_keys
      mode: '0600'
      owner: borg
      group: borg
