---

  - name: copy script.sh
    template:
       src: files/borg-backup.service
       dest: /home/script.sh

  - name: inicial repo /var/backup
    shell: sh /home/script.sh

  - name: copy file borg-backup.service
    template:
       src: files/borg-backup.service
       dest: /etc/systemd/system/

  - name: copy file borg-backup.timer
    template:
       src: files/borg-backup.timer
       dest: /etc/systemd/system/

  - name: enable borg-backup.timer
    service:
      name: borg-backup.timer
      state: started 
      enabled: yes

  - name: hr hr hr 
    shell: sleep 10

  - name: enable borg-backup.service
    service:
      name: borg-backup.service
      state: started 
      enabled: yes