---
# tasks file for client

  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: install borg_backup
    yum:
      state: present
      name:
        - borgbackup

  - name: Generate /etc/ssh/ RSA host key
    command : ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -C "" -N ""
    args:
      creates: /root/.ssh/id_rsa

  - name: Extract file
    fetch:
      src: /root/.ssh/id_rsa.pub
      dest: ./roles/backup/files/